# -*- coding: utf-8 -*-
"""Area of the circle .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tvf66IzjfTrIDszfYezRw95RVGsIqeo4
"""

def area_of_circle(radius):
    """
    this function calculates the area of the circle
    """

    pi = 3.14
    area = pi * (radius ** 2)
    return area

answer = area_of_circle(54)
print("The answer is:", answer)