# -*- coding: utf-8 -*-
"""area of triangel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSbB1GQiC_-U09PfClOxNwZet8n8P-j2
"""

def area_of_triangle(base, height):
 """
 This function calculates the area of triangle
 """
 area = base * height
 return area

area = area_of_triangle(23, 4)

print("The area is equal to:", area)