# -*- coding: utf-8 -*-
"""Average.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xE0VrIVkFD7ZAys-bwHPQyN7_y-jJmqj
"""

def average_of_three(a, b, c):
    """
    This is the fuction that calculate the average of three
    """

    average_of_three = (a + b + c)/3
    return average_of_three

average = average_of_three(23, 478, 16)/3
print("The average is:", average)