# -*- coding: utf-8 -*-
"""Base & Exponent .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CT8WUT4k_fcFCocdpLYFA92tBx-3257
"""

def calculate_power(base, exponent):
  """
  This is the fuction that calculate power
  """
  result = base ** exponent
  return result

my_result = calculate_power(4, 5)
print("The result is:", my_result)