# -*- coding: utf-8 -*-
"""celsius_to_fahrenheit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fH47G2yWaiCc0_5PpNmflbitJx8J4Iz4
"""

def celsius_to_fahrenheit(c_temp):
    """
    This function converts celsius-to_fahrenheit
    """

    f_temp=(c_temp*9/5)+32
    return f_temp

solution = celsius_to_fahrenheit(23)
print("This is the solution:", solution)