# -*- coding: utf-8 -*-
"""Distance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1e36ElTVjCLWJ9txeIBdgQvitO6bi2f
"""

import math
def find_distance(x1, y1, x2, y2):
    """
    This function calculates the distance between two points
    """
    distance = math.sqrt(x2-x1)**2 + (y2-y1)**2
    return distance

distance = find_distance(-23, 32, 56, 49)
print("The distance between two points is:", distance)