# -*- coding: utf-8 -*-
"""even.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13XB1JxNNXHJ_FPoWdOq52UsjdGah8Nah
"""

def is_even(number):
    """
    This function returns true if the number is even, false if it's odd
    """

    if number % 2 == 0:
      return True
    else:
      return False
number = is_even(2925)
print("The number is:", number)