# -*- coding: utf-8 -*-
"""factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7CpHtsshOfpW1LKK_ir0_5KShfThI7b
"""

def factorial(n):
    """
    this function calculates the loop using n
    """

    result = 1
    for i in range(1, n+1):
        result = result * i
    return result

my_factorial = factorial(6)
print("factorial:", my_factorial)