# -*- coding: utf-8 -*-
"""feet_to_meters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rvFmqP8YkL0lVhBpJ7BMMg_n4JYjui0
"""

def feet_to_meters(feet):
    """
    This function convert feet to meters
    """

    meter = feet * 0.3048
    return meter

the_feet = feet_to_meters(234)
print("The solution is:", the_feet)