# -*- coding: utf-8 -*-
"""hypotenuse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jl3xaVUBmlwiXMOGe7Q-uP7ybCoMS0TX
"""

import math

def find_hypotenuse(a, b):
    """
    This function finds the length of the hypotenuse of a right_angled triangle
    """

    c = math.sqrt(a**2 + b**2)
    return c

c = math.sqrt(2 + 7)
print("The hypotenuse is equal to:", c)