# -*- coding: utf-8 -*-
"""Maximum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1msXYZKrWgVyHegIX4mHzacpXam8RVzdX
"""

def find_max(num1, num2):
    """
    This function calculates the maximum of two without using max()
    """

    if num1 > num2:
      return num1
    else:
      return num2

maximum = find_max(2456, 2025)
print("The maximum is equal to:", maximum)