# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPbjacL863hSHyuS-w2EM7K6v6W_OvAS
"""

def is-prime(number)
    """
    This fuction returns True if the number is prime
    """