# -*- coding: utf-8 -*-
"""percentage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9Dafe4bbD4DJTIeN7cRWltHA8ocM_AC
"""

def find_percentage(part, whole):
    """
    This function works as a percentage calculator
    """

    percentage = (part / whole) * 100
    return percentage

the_percentage = find_percentage(1246, 20)
print("1246 out of 20 is:", the_percentage)