# -*- coding: utf-8 -*-
"""perimeter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQcaBxD2mpO_RnA3rMyf3q6yxhQKYSX9
"""

def perimeter_of_square(side):
  """
  This function calculates the perimeter if a square
  """

  perimeter = 4 * side
  return perimeter

my_solution = perimeter_of_square(55)
print("The perimeter is:", my_solution)