# -*- coding: utf-8 -*-
"""Prime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPbjacL863hSHyuS-w2EM7K6v6W_OvAS
"""

def is_prime(number):

    """
    This fuction returns True if the number is prime
    """

    if number < 2:
        return False

    for i in range(2, int(number**0.5)+1):
        if number % i == 0:
           return False
    return True

prime = is_prime(23)
print("The prime is:", prime)