# -*- coding: utf-8 -*-
"""simple interest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYW_GSxF5X4o9NSCdpL17oCbhIoPqdu9
"""

def calculate_simple_interest(principal, rate, time):
 """
 This function calculates the simple interest
 """
 si = (principal * rate * time) /100
 return si

si = calculate_simple_interest(12000000, 20, 12)/100
print("the simple interest is:", si)