# -*- coding: utf-8 -*-
"""Slope.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPauJb5Kh-4EnPJdvbs6gsSnN4aasdtA
"""

def find_slope(x1, y1, x2, y2):
    """
    This function calculates the slope of a line
    formula: slope= y2-y1/x2-x1
    """
    slope = y2-y1/x2-x1
    return slope

slope = find_slope(12, 14, 24, -12)
print("The slope of s line is:", slope)