# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jTM0uvpglB1acedmdktjEQRTqVqQQcD
"""

def is_solution(x, y):
    """
    The function check if the (x,y) point satisfies both:
    2*x + 3*y = 12
    x - y = 1
    return True or False
    """

    eq1 = 2*x + 3*y
    eq2 = x - y

    if eq1 == 12 and eq2 == 1:
        return True
    else:
        return False

my_solution = is_solution(2, 3)
print("It's:", my_solution)