# -*- coding: utf-8 -*-
"""welcome_student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_V8aw6rzGPiSOWwdKv23v-23lV8NVO9
"""

def welcome_student(name):
  """
  Takes a student's name and return a welcome message
  """

  message = "Hello " + name + " welcome to the maths class"
  return message

print(welcome_student("bob"))